name: Python Test

on: [push] 
jobs:   
  build:     
  
    runs-on: ubuntu-latest     
    
    steps:       
      - uses: actions/checkout@v3       
      - name: Set up Python 3.11         
        uses: actions/setup-python@v4         
        with:           
          python-version: '3.11'       
      - name: Install dependencies         
        run: |           
          python -m pip install --upgrade pip   
          pip install pytest coverage    
      
      - name: Test         
        run: python -m pytest

      - name: Measure coverage with PyTest   
        run: | 
          coverage run --branch -m pytest    
          coverage report      
          coverage json 
      
      - name: Coverage Badge   
        uses: tj-actions/coverage-badge-py@v2 